version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: sosa_postgres
    restart: always
    environment:
      POSTGRES_DB: sosa_db
      POSTGRES_USER: whyy0u
      POSTGRES_PASSWORD: whyy0u_super_passwdlzo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    networks:
    - sosa_net


  # backend:
  #   build: ./backend
  #   container_name: sosa_backend
  #   restart: always
  #   depends_on:
  #     - postgres
  #   expose:
  #     - "8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sosa_db
  #     SPRING_DATASOURCE_USERNAME: whyy0u
  #     SPRING_DATASOURCE_PASSWORD: whyy0u_super_passwdlzo
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1g
  #       reservations:
  #         memory: 512m
  #   networks:
  #     - sosa_net


  # nginx:
  #   image: nginx:alpine
  #   container_name: sosa_nginx
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./frontend/dist:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256m
  #       reservations:
  #         memory: 128m
  #   networks:
  #     - sosa_net


volumes:
  postgres_data:

networks:
  sosa_net:
    driver: bridge
