version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: sosa_postgres
    restart: always
    environment:
      POSTGRES_DB: sosa_db
      POSTGRES_USER: whyy0u
      POSTGRES_PASSWORD: whyy0u_super_passwdlzo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    networks:
    - sosa_net


  backend:
    build: ./backend
    container_name: sosa_backend
    restart: always
    depends_on:
      - postgres
      - ollama
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sosa_db
      SPRING_DATASOURCE_USERNAME: whyy0u
      SPRING_DATASOURCE_PASSWORD: whyy0u_super_passwdlzo
      OLLAMA_BASE_URL: http://ollama:11434
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    networks:
      - sosa_net


  nginx:
    image: nginx:alpine
    container_name: sosa_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m
    networks:
      - sosa_net


  ollama:
    image: ollama/ollama:latest
    container_name: sosa_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama serve & sleep 5 && ollama pull qwen2.5:3b && wait"]
    deploy:
      resources:
        limits:
          memory: 6g
        reservations:
          memory: 3g
    networks:
      - sosa_net
    # Для GPU (NVIDIA) раскомментируйте:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]


volumes:
  postgres_data:
  ollama_data:

networks:
  sosa_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
